name: 'Commerce Kickstart: Base'
description: 'Commerce Kickstart is to start building on Drupal Commerce'
type: 'Commerce'
recipes:
  # This recipe doesn't currently use Standard recipe but only some of the recipes utilized by the Standard recipe.
  - core/recipes/basic_block_type
  - core/recipes/comment_base
  - core/recipes/page_content_type
  - core/recipes/user_picture
  - core/recipes/administrator_role
  - core/recipes/basic_html_format_editor
  - core/recipes/full_html_format_editor
  - core/recipes/restricted_html_format
  # Installation of Commerce Core and most of the modules.
  - commerce_recipe_core
install:
  # Modules that were not installed by commerce_recipe_core.
  - commerce_promotion
  - commerce_tax

  # Core
  - file
  - user
  - node
  - history
  - big_pipe
  - block
  - breakpoint
  - ckeditor5
  - config
  - comment
  - contextual
  - menu_link_content
  - datetime
  - block_content
  - editor
  - help
  - image
  - menu_ui
  - options
  - path
  - dynamic_page_cache
  - taxonomy
  - dblog
  - shortcut
  - toolbar
  - field_ui
  - views_ui
  - automated_cron

  # Contrib
  - pathauto
  - admin_toolbar
  - admin_toolbar_tools
  - config_split
  - facets
  - facets_pretty_paths
  - symfony_mailer

  # Themes
  - belgrade
  - centarro_claro
config:
  strict: false
  import:
    commerce_promotion: '*'
    commerce_tax: '*'
    file: '*'
    filter: '*'
    # To avoid installing search module's optional config, list of config was composed manually.
    user:
      - core.entity_form_mode.user.register
      - core.entity_view_mode.user.compact
      - core.entity_view_mode.user.full
      - system.action.user_block_user_action
      - system.action.user_cancel_user_action
      - system.action.user_unblock_user_action
      - user.flood
      - user.mail
      - user.role.anonymous
      - user.role.authenticated
      - user.settings
      - views.view.user_admin_people
      - views.view.who_s_new
      - views.view.who_s_online
    node:
      - core.entity_view_mode.node.full
      - core.entity_view_mode.node.rss
      - core.entity_view_mode.node.search_index
      - core.entity_view_mode.node.search_result
      - core.entity_view_mode.node.teaser
      - field.storage.node.body
      - node.settings
      - system.action.node_delete_action
      - system.action.node_make_sticky_action
      - system.action.node_make_unsticky_action
      - system.action.node_promote_action
      - system.action.node_publish_action
      - system.action.node_save_action
      - system.action.node_unpromote_action
      - system.action.node_unpublish_action
      - views.view.archive
      - views.view.content
      - views.view.content_recent
      - views.view.frontpage
      - views.view.glossary
    history: '*'
    big_pipe: '*'
    block: '*'
    breakpoint: '*'
    ckeditor5: '*'
    config: '*'
    comment: '*'
    contextual: '*'
    menu_link_content: '*'
    datetime: '*'
    block_content: '*'
    editor: '*'
    image: '*'
    menu_ui: '*'
    options: '*'
    dynamic_page_cache: '*'
    taxonomy: '*'
    dblog: '*'
    shortcut: '*'
    toolbar: '*'
    field_ui: '*'
    views_ui: '*'
    pathauto: '*'
    admin_toolbar: '*'
    admin_toolbar_tools: '*'
    config_split: '*'
    facets: '*'
    facets_pretty_paths: '*'
    symfony_mailer: '*'
    belgrade: '*'
    centarro_claro: '*'
    claro: '*'
  actions:
    node.settings:
      simpleConfigUpdate:
        use_admin_theme: true
    system.site:
      simpleConfigUpdate:
        page.front: /node
    user.settings:
      simpleConfigUpdate:
        verify_mail: false
        register: visitors
        cancel_method: user_cancel_block
    user.role.anonymous:
      grantPermissions:
        - 'access content'
        - 'access comments'
    user.role.authenticated:
      grantPermissions:
        - 'access content'
        - 'delete own files'
        - 'access comments'
        - 'post comments'
        - 'skip comment approval'
    system.theme:
      simpleConfigUpdate:
        default: belgrade
        admin: centarro_claro
